print("O que e python ?")
print("Oi meu nome e python /n sou uma linguagem de programacao com codigo aberto !")
print("Qual programa (IDE) executa o arquivo.py ?")
print("O vscode e responsavel por executar o arquivo.py")
print("Qual linguagem de programacao python substituiu ?")
print("A linguagem que o python subistituiu foi a linguagem ABC !")